# Generated by Django 4.2.6 on 2023-11-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("df_survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="format",
            field=models.TextField(blank=True, default=""),
        ),
    ]
