# Generated by Django 4.2.6 on 2023-10-18 11:08

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):
    dependencies = [
        ("df_survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="id",
            field=hashid_field.field.BigHashidAutoField(
                alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                auto_created=True,
                min_length=13,
                prefix="",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="id",
            field=hashid_field.field.BigHashidAutoField(
                alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                auto_created=True,
                min_length=13,
                prefix="",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="surveystep",
            name="id",
            field=hashid_field.field.BigHashidAutoField(
                alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                auto_created=True,
                min_length=13,
                prefix="",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="usersurvey",
            name="id",
            field=hashid_field.field.BigHashidAutoField(
                alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                auto_created=True,
                min_length=13,
                prefix="",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="usersurveystep",
            name="id",
            field=hashid_field.field.BigHashidAutoField(
                alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                auto_created=True,
                min_length=13,
                prefix="",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
