# Generated by Django 4.2.6 on 2023-11-17 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("df_survey", "0002_surveyquestion_alter_surveytemplate_task_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surveyquestion",
            old_name="options",
            new_name="type",
        ),
    ]
