# Generated by Django 4.2.6 on 2023-11-20 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("df_survey", "0003_alter_question_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyquestion",
            options={"ordering": ("sequence",)},
        ),
        migrations.AlterUniqueTogether(
            name="surveyquestion",
            unique_together={("survey", "question")},
        ),
    ]
